const PORT = 8080;
const JWT_KEY =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTcwNTQxMDc2NywiZXhwIjoxNzA1NDE0MzY3fQ.u5J8XaOA2UC3jd8PAfOclvCrFvogNyYAFsyzlckbjP4";

export { JWT_KEY, PORT };
